name: dan_utils
description: Dan Utils is Package Utils for Dart and Flutter
version: 0.1.0
homepage: https://pujandan.com
repository: https://github.com/pujandan/dan-utils

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
